use_frameworks!

target 'Supports_Example' do
  pod 'Supports', :path => '../'

  target 'Supports_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
